apiVersion: apps/v1
kind: Deployment
metadata:
  name: devsecops-app
spec:
  replicas: 2
  selector:
    matchLabels:
      app: devsecops
  template:
    metadata:
      labels:
        app: devsecops
    spec:
      containers:
      - name: app
        image: nitin115/app:latest
        ports:
        - containerPort: 3000
      imagePullSecrets:
      - name: dockerhub-secret
